### ISSUE TITLE
ScrollViews doesn't scroll properly

### ISSUE THREAD

**Issue by meekmika** [jpapillon/react-native-carousel-pager#12]
Hi!
I'm just starting out with React Native and I'm really glad I stumbled upon your carousel, it looks great!

I'm having issues when I pass in ScrollViews to the CarouselPager.

I want to be able to scroll vertically when there's text that won't fit on the page.

What I have is essentially something like this:

```
<CarouselPager>
  <ScrollView key={'page0'}><Text>{/* A lot of text */}</Text></ScrollView>
  <ScrollView key={'page1'}><Text>{/* A lot of text */}</Text></ScrollView>
  <ScrollView key={'page2'}><Text>{/* A lot of text */}</Text></ScrollView>
</CarouselPager>
```
Behavior:
**iOS:** Scrolling between the pages works fine but scrolling vertically doesn't work at all
**Android:** It's possible to scroll vertically but scrolling between the pages isn't as smooth and it "gets stuck"

It's the same thing when I wrap the ScrollViews in Views.

Is there a way to fix this?

**Comment by jpapillon** [comment]
Hi @meekmika, I just fixed that. Let me know if you experience any other issues. Thanks!
