### ISSUE TITLE
Is there a way to get the current displayed page ?

### ISSUE THREAD

**Issue by WeberJulian** [jpapillon/react-native-carousel-pager#4]
Hi, I'm new to react native, forgive me if the answer is obvious.
First off, nice work with the animation !
I was wondering if there is a way to get an event or a variable containing the number of the page that has the focus ? I need to make an animation depending of the current page .
I see that in the code there is a _currentPage variable, but I don't know how to access it from my component.
Thanks in advance for the help

**Comment by jpapillon** [comment]
Hi @WeberJulian, thanks for using my plugin. I'm going to add a callback whenever a page changes, so you'll know exactly on which page we are.

**Comment by WeberJulian** [comment]
![currentpage](https://user-images.githubusercontent.com/17219561/32678318-31a9bf12-c662-11e7-9e1a-091a75e440fc.gif)
I made this, do you want me to do a pull request ?

**Comment by jpapillon** [comment]
@WeberJulian Thanks! Let me review and merge this!

**Comment by jpapillon** [comment]
This has been merged with https://github.com/jpapillon/react-native-carousel-pager/pull/5
