### ISSUE TITLE
Click Event on carousel

### ISSUE THREAD

**Issue by muku01** [jpapillon/react-native-carousel-pager#6]
Hi,

I've just started to react native and I used your carousel pager. But  I have a problem. I didn't add click event on the card. How can I do it? Can you help me about this issue ? I am waiting your reply. Thanks.

**Comment by jpapillon** [comment]
Hi @muku01, have you tried something like that?
```
<CarouselPager initialPage={2} pageStyle={{backgroundColor: '#fff'}}>
  <View key={'page0'}><TouchableOpacity onPress={() => {/* Clicked page 0 */}}><View style={{flex: 1}} /></TouchableOpacity></View>
  <View key={'page1'}><TouchableOpacity onPress={() => {/* Clicked page 1 */}}><View style={{flex: 1}} /></TouchableOpacity></View>
  <View key={'page2'}><TouchableOpacity onPress={() => {/* Clicked page 2 */}}><View style={{flex: 1}} /></TouchableOpacity></View>
  <View key={'page3'}><TouchableOpacity onPress={() => {/* Clicked page 3 */}}><View style={{flex: 1}} /></TouchableOpacity></View>
</CarouselPager>
```

**Comment by petroslafaz** [comment]
Hi @muku01 @jpapillon ,

@jpapillon suggestion requires to change PanResponder's behaviour a bit, essentially:
onMoveShouldSetPanResponder has to return true, i.e:

`      onMoveShouldSetPanResponder: (evt, gestureState) => true,
`

**Comment by jpapillon** [comment]
Hi @petroslafaz, if you take a look at https://github.com/jpapillon/react-native-carousel-pager/pull/7, it was set to `false` to allow links inside the carousel. I will take a look at this and find the best way to allow both functionalities.

**Comment by petroslafaz** [comment]
Hi @jpapillon ,

Thanks for prompt response, and for putting together this component.
I see. In my case I need to be able to turn pages to touchables as seen below:
![ezgif-1-b71ef24bd2](https://user-images.githubusercontent.com/483710/33435813-1248fdee-d5db-11e7-9323-1530cf9aca0b.gif)

**Comment by jpapillon** [comment]
@petroslafaz : have you tried something like this: https://github.com/jpapillon/react-native-carousel-pager/issues/6#issuecomment-345332447 ? You would have full control on the Touchable event by putting the content of each page inside, thus having your whole pages clickable. For example:
```
<CarouselPager initialPage={2} pageStyle={{backgroundColor: '#fff'}}>
  <View key={'page0'}>
    <TouchableOpacity onPress={() => Alert.alert('Page0'}>
      <View style={{flex: 1, backgroundcolor: '#000'}}>
        {/* your page0 content here */}
      </View>
    </TouchableOpacity>
  </View>
  {/* your other pages */}
</CarouselPager>
```

You could try this in the meantime. I will add an "onPagePress" prop that will do exactly as you wish if provided.

**Comment by petroslafaz** [comment]
@jpapillon Yes this is exactly what I'm using now. But I needed to change the _onMoveShouldSetPanResponder_ as mentioned before for the panning to work. Otherwise the Touchables take hold of the gesture and the panning stops working

**Comment by jpapillon** [comment]
@petroslafaz Ok, I will take a deeper look into this and make sure it works for both functionalities. Thanks!
